#!/usr/bin/env php
<?php

require __DIR__ . DIRECTORY_SEPARATOR . 'vendor/autoload.php';

use Hasher\HasherCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$command = new HasherCommand();

$application->add($command);
$application->setDefaultCommand($command->getName(), true);

$application->run();